# Secret containers are created by Terraform; the sensitive *values* come
# from Terraform variables (slack_webhook_url, gemini_api_key -- populated
# from GitHub Actions repo secrets, never committed) or, for the DB
# password, are generated by Terraform itself (see cloud_sql.tf). Only the
# api service can read any of these (see iam.tf).

resource "google_secret_manager_secret" "slack_webhook_url" {
  secret_id = "cloudwatcher-slack-webhook-url"

  replication {
    auto {}
  }

  depends_on = [google_project_service.required]
}

resource "google_secret_manager_secret_version" "slack_webhook_url" {
  secret      = google_secret_manager_secret.slack_webhook_url.id
  secret_data = var.slack_webhook_url
}

resource "google_secret_manager_secret" "gemini_api_key" {
  secret_id = "cloudwatcher-gemini-api-key"

  replication {
    auto {}
  }

  depends_on = [google_project_service.required]
}

resource "google_secret_manager_secret_version" "gemini_api_key" {
  secret      = google_secret_manager_secret.gemini_api_key.id
  secret_data = var.gemini_api_key
}

resource "google_secret_manager_secret" "db_password" {
  secret_id = "cloudwatcher-db-password"

  replication {
    auto {}
  }

  depends_on = [google_project_service.required]
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db.result
}
