"""add billing, anomaly, and alert config tables

Revision ID: 8a2da697d426
Revises: 
Create Date: 2026-09-23 19:07:38.254309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2da697d426'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('z_threshold', sa.Float(), server_default='3.0', nullable=False),
    sa.Column('slack_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expected_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('pct_deviation', sa.Float(), nullable=False),
    sa.Column('top_contributor', sa.String(length=255), nullable=True),
    sa.Column('root_cause_explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_date'), 'anomalies', ['date'], unique=False)
    op.create_index(op.f('ix_anomalies_service'), 'anomalies', ['service'], unique=False)
    op.create_table('billing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_records_account_id'), 'billing_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_billing_records_date'), 'billing_records', ['date'], unique=False)
    op.create_index(op.f('ix_billing_records_provider'), 'billing_records', ['provider'], unique=False)
    op.create_index(op.f('ix_billing_records_service'), 'billing_records', ['service'], unique=False)
    op.create_table('daily_service_costs',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('date', 'provider', 'service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_service_costs')
    op.drop_index(op.f('ix_billing_records_service'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_provider'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_date'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_account_id'), table_name='billing_records')
    op.drop_table('billing_records')
    op.drop_index(op.f('ix_anomalies_service'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_date'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('alert_config')
    # ### end Alembic commands ###
