"""optimize billing indexes for actual query patterns

Revision ID: fdddcdc1f7a2
Revises: 8a2da697d426
Create Date: 2026-10-01 01:06:16.358886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdddcdc1f7a2'
down_revision: Union[str, None] = '8a2da697d426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_records_date'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_service'), table_name='billing_records')
    op.create_index('ix_billing_records_service_date', 'billing_records', ['service', 'date'], unique=False)
    op.create_index('ix_daily_service_costs_service_date', 'daily_service_costs', ['service', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_service_costs_service_date', table_name='daily_service_costs')
    op.drop_index('ix_billing_records_service_date', table_name='billing_records')
    op.create_index(op.f('ix_billing_records_service'), 'billing_records', ['service'], unique=False)
    op.create_index(op.f('ix_billing_records_date'), 'billing_records', ['date'], unique=False)
    # ### end Alembic commands ###
